# -*- coding: utf-8 -*-
"""decision_tree 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8LSCpBKy3D95EvY1OnSV3NFm6vvsgHd

BUY THE LAPTOP OR NOT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import(mean_absolute_error,mean_squared_error,r2_score)
data=pd.read_csv("/content/laptop_purchase_dataset.csv")
data

data.head()

data.tail()

data.info()

data.describe()

data.isnull().sum()
data.fillna(method='ffill',inplace=True)
data.isnull().sum()
data.head()

fill=data.fillna(6)
fill

data["BuyLaptop"].value_counts()

encoder=LabelEncoder()
data["Salary"]=encoder.fit_transform(data["Salary"])
data["Student"]=encoder.fit_transform(data["Student"])
data["BuyLaptop"]=encoder.fit_transform(data["BuyLaptop"])
data.head()

a=data.drop(["Salary","CustomerID"],axis=1)
b=data["Salary"]
a

x_train, x_test, y_train, y_test = train_test_split(a, b, test_size=0.2, random_state=42)

model=DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

model.fit(x_train, y_train)

predictions=model.predict(x_train)
predictions