# -*- coding: utf-8 -*-
"""Linear_re.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0yNQ3BhgrOw3bMRdNv2_hYfV8scK7d3

SALARY PREDICTION USING LINEAR REGRESSION
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import(mean_absolute_error,mean_squared_error,r2_score)
data=pd.read_csv("salary_dataset.csv")
data

data.head()

data.tail()

data.shape

data.info()

data.describe()

data.isnull().sum()

data.columns

data.loc[3]

data.iloc[2]

X = data.drop("Salary", axis=1) # Features for salary prediction
y = data["Salary"]             # Target for salary prediction
X # Display features

categorical = X.select_dtypes(include="object").columns
categorical

preprocessor = ColumnTransformer(
    transformers=[
        ("cat",
        OneHotEncoder(handle_unknown="ignore", sparse_output=False),
        categorical)
    ],
    remainder="passthrough"
)

model=Pipeline(
    steps=[("preprocessor",preprocessor),
         ("regression",LinearRegression())

    ]
)

df_train, df_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(df_train,y_train)

prediction=model.predict(df_test)
prediction[:10]

mae=mean_absolute_error(y_test,prediction)
mae