# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxrD8-DqDSLPPid3g175Y9heFmW9AB9i

NUMPY
"""

import numpy as np
arr=np.array([[3,4,6,7,6],
              [3,8,9,5,5]])
print(arr)

import numpy as np
lst=[1,2,3,4,5,6]
arr=np.array(lst)
print(arr)
print(np.mean(arr))
print(np.sum(arr))
print(lst*2)
print(arr.shape)
print(arr.ndim)

arr=np.array([[[3,4,6,7,6],
              [3,8,9,5,5],
              [23,44,55,78,33]]])
print(arr)
print(arr.shape)
print(arr.ndim)

n=np.zeros(5)
print(n)
p=np.ones((5,3))
print(p)
g=np.arange(1,11,2)
print(g)
rand=np.random.rand(6)*8
print(rand)
p

g=np.arange(0,18)
print(g.reshape(3,6))
print(g.flatten())

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,19])
a=np.where(arr%2==0)
print(a)

a=np.array([[1,2,3],[2,3,4],[8,4,4]])
b=np.array([[7,8,9],[9,6,5],[4,6,7]])
print(np.dot(a,b))

col=np.array([23,2220,2550,2677,2590,22,46])
fil=(col[col>2000])
print(fil)
avg=np.mean(fil)
print(avg)

score=np.array([23,56,55,67,90,45,96])
norm=score-min(score)/max(score)-min(score)
print(norm)
print(max(score))

cam=np.array([23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6])
a=cam.reshape(6,3)
print(a)
b=a.transpose()
print(b)
print(np.dot(a,b))
c=np.array([22,3,4,5,6,6,65,5,5,4,3,28])
d=c.reshape(6,2)
print(d)
print(np.dot(b,d))

"""PANDAS"""

import pandas as pd
df=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(df)

data={
    "name":["Alex","sundu","SUNDAR","RAM"],
    "SAl":[25000,45000,30000,23333],
    "usn":[1,2,3,4],
    "cities":["mangalore","bangalore","goa","udupi"]
}
a=pd.DataFrame(data)
print(a)
a.head(2)
a.tail(2)
a.describe()
a.info()
a.shape
a.columns

a['SAl'].head(2)
a[['cities','name']].tail(3)
a.loc[2]
a.iloc[3]

data={
    "name":["Alex","sundu","SUNDAR","RAM"],
    "SAl":[25000,45000,30000,23333],
    "usn":[1,2,3,4],
    "cities":["mangalore","bangalore","goa","udupi"]
}
a=pd.DataFrame(data)
print(a)
a.head(2)
a.tail(2)
a.describe()
a.info()
a.shape
a.columns

a['bonus']=[1000,2000,30000,40000]
a.head()
a.loc[1,'SAl']=1000000
a

a["department"]=["it","hcr","it","hcr"]
a.groupby(["department"])["SAl"].mean()

import pandas as pd
df=pd.Series()

import numpy as np
temperatures = pd.Series([25, 26, np.nan, 28, 27, 29, np.nan, 30, 26, 25])
temperatures

missing = temperatures.isnull()
missing

avg=temperatures.mean()
avg

fill=temperatures.fillna(avg)
fill